baseurl = "https://HaipengU.github.io/"
title = "Haipeng Yu"
copyright = "&copy; Haipeng Yu"
theme = "academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = []
preserveTaxonomyNames = true
paginate = 10

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable analytics by entering your Google Analytics tracking ID
 googleAnalytics = ""

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false


[outputs]
  home = [ "HTML", "CSS", "RSS" ]
  section = [ "HTML", "RSS" ]

[permalinks]
post = "/blog/:year/:month/:filename"

[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab.
  fractions = true  # `false` disables smart fractions (e.g. 5/12 formatted as a fraction).
  smartypants = true  # `false` disables all smart punctuation substitutions (e.g. smart quotes, dashes, fractions).

[outputFormats.RSS]
baseName = "feed"

[params]
  #   Choose from `default`, `ocean`, `forest`, `coffee`, `dark`, `vt`, `isu`, `uf`. 
  color_theme = "uf"
  #   Choose from `default`, `classic`, or `playfair`.
  font = "default"
  name = "Haipeng Yu"
  role = "Assistant Professor"
  organizations = [{name = "University of Florida", url = "" }]
  gravatar = false
  avatar = "HY.png"
  email = "haipengyu@ufl.edu"
  address = "2250 Shealy Dr. Gainesville, FL 32611"
  office_hours = ""
  phone = ""
  skype = ""
  telegram = ""

  # Enable Keybase in Contact section by entering your keybase.io username.
  keybase = ""
  logo = ""
  map = ""
  map_api_key = ""
  latitude = "37.231264"
  longitude = "-80.426745"
  zoom = 9
  
  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "2006-01-02"
  time_format = "3:04 PM"

  reading_time = false
  comment_count = false
  section_pager = false

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = false

  highlight = true
  highlight_languages = ["r", "python"]
  # highlight_style = "github"
  # Enable native social sharing buttons?
  sharing = false

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []

  publication_types = [
    'Uncategorized',  # 0
    'Conference proceedings',  # 1
    'Journal',  # 2
    'Work in progress',  # 3
    'Technical report',  # 4
    'Book',  # 5
    'Book chapter'  # 6
  ]

  [params.publications]
    # Date format (refer to Go's date format: http://fuckinggodateformat.com )
    #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
    date_format = "2006-01-02"

# Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  #[[params.social]]
    #icon = "envelope"
    #icon_pack = "fa"
    #link = "mailto:hpyu@iastate.edu"
  
  [[params.social]]
    icon = "github"
    icon_pack = "fab"
    link = "https://github.com/HaipengU"
    
  [[params.social]]
    icon = "google-scholar"
    icon_pack = "ai"
    link = "https://scholar.google.com/citations?user=JdcOaX0AAAAJ&hl=en"
   
  [[params.social]]
    icon = "orcid"
    icon_pack = "ai"
    link = "https://orcid.org/0000-0002-8923-9733" 
    
  [[params.social]]
    icon = "publons"
    icon_pack = "ai"
    link = "https://www.webofscience.com/wos/author/record/2031351"  
  
  [[params.social]]
    icon = "twitter"
    icon_pack = "fab"
    link = "https://twitter.com/HaipengU"

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fab"
    link = "https://www.linkedin.com/in/haipeng-yu/"

  # [[params.social]]
  #  icon = "rss"
  #  icon_pack = "fa"
  #  link = "feed.xml"


# Navigation Links
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Publications"
  url = "#publications"  # change to #preprints when preprints are available (activate via home/preprints.md). 
  weight = 2

[[menu.main]]
  name = "Software"
  url = "#software"
  weight = 3

# [[menu.main]]
#  name = "Posts"
#  url = "#posts"
#  weight = 4

[[menu.main]]
  name = "Teaching"
  url = "#teaching"
  weight = 5

[[menu.main]]
  name = "CV"
  url = "cv/yu.pdf"
  weight = 6

 [[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 7

[Languages.en]
  languageCode = "en-us"
